travis:
  secure:
    BINSTAR_TOKEN: kTo4TPg/KmSHzT0sG14pLl/pOQtjQlnzKbLmC7Vo/VEmN5cnh9WK4kn4jg4rCew/cShlRdXOZlHW4uehhM8LGMlWUuJ2cTpRh7coreqwTyJbxqVG03UoXmLVqXUMc4T/9RVheFcpZKIFaYl9XnsSud6+oXsWHafirUCmL++xFaWtZ+qQiUH7ynzGDplQ1RrRn4/T/S4zjPa6vR6gIYBqQcJgtj3n+Gq0KemUwwTGQhddYBwFxwzQAEGOMTCp9DTSC0gQXDE8kpOToM2gohaCMD4oYJk+vZarOtUkw6jR4l/COp8vFDvMMkT+Bf0gIdpbbbu0dwbxA1PZluQHMFBiNni+IO8oGVHxu9C+Hn0qU2y6UjEz0VsSy7KEYbKbalUNPNDwESPNEgSNpZBACGiZX6erRbE+ov2i0Rj5lOkkrckfa3+cYFcNpFpF2/rJVoww9QHS0rgIKK+lXtCMcUhe6SqeY4G8CQ5j1Ju0YVDqoqIRlOG6y2exqZqdcykrKMarV0lEp/OwtSQPRQTkNfIViB2Gg5VYlVK9Emf4oN4WB5TbycMsRl3ocVACgpBV4oBRTTzq8waaCQiPzv7IUoZPoYT4GCcd8AcbYkZOjQUy0z4qxNU26Kdhw4NQyvjtBG8nX4GwmJ7eEY8Y4RvWF61AIHt89UwrPgQ92LF+EUIS01k=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
